
ingress:
  console_dns: console.lukasz.test
  kas_dns: kas.lukasz.test
  
  annotations:
    cert-manager.io/cluster-issuer: plural
  


provider: byok


secrets:
  jwt: b4N4Wk2etSYCFbMdf5Ft0jvr8sPzNmxXWknrWFhBnA0=
  admin_name: lukasz@plural.sh
  aes_key: zYLle3qHH4Mbo5E9Ooo8tqHCEYd6_2s15E9NAslmFOI=
  erlang: u1MKb6enXFIEzFp6w4kgoYlCfCrPhqrItBAvHxv10AhpIhdghmmpTQFTaeDhDKxr
  admin_email: lukasz@plural.sh
  admin_password: 550QuwzJh60qsx6EkrUyG/TWSe/uDPByZHjtzJ4+2uo=
  cluster_name: lukasz
  git_url: git@github.com:zreigz/empty.git
  
  plural_client_id: 1ee86f34-c3c2-40bf-b8c8-23fd3b4da080
  
  
  plural_client_secret: 1Y-7Yjm1~u0HlaBa8PibWZEE7A
  
  
  key: "key: e8GvCP4iZ97uP9MXu5cAm+88M2G5Bqljlh3by2SbPrU=\n"
  
  
  identity: "# created: 2022-08-03T16:05:00+02:00\n# public key: age1wqc2hk954ukemelys5gxdwlqve8ev0e88hvl3cjhfcvq65gwgvsqkmq9dn\nAGE-SECRET-KEY-13XTF9482T0WVVN0C4G65NCGQG0CXTV6UXELW70QKAQVGP9G7MNJQ2F5Z9G\n"
  

extraSecretEnv:
  PLURAL_TOKEN: plrl-j-0P1WJ3sBwdXnjYPKM0sdAp74JTsjwCpPQ6l9n4xaodfa2PU5DQccwRcQi8MjK38i5NmVUeilw0jemB_rDIXw==
  KAS_API_SECRET: SibvhBnMDoQaVowhtrIxuI0bHQLIi6chGVYrY6bQ8B4=
  KAS_PRIVATE_API_SECRET: CIHaX9v6ps79IHANMutNxu7YmL9iE/54VWLLlRdJGkk=
  KAS_REDIS_SECRET: F0r/4w0QLv+qe9xb0045ql/SraeNHxPCzTm7mFFOaPk=
  POSTGRES_URL: postgres://postgres:mysecretpassword@my-postgres-postgresql.default.svc.cluster.local:5432/postgres
  CONSOLE_BYOK: 'true'

kas:
  enabled: true
  consoleUrl: console.lukasz.test

  secrets:
    api: SibvhBnMDoQaVowhtrIxuI0bHQLIi6chGVYrY6bQ8B4=
    privateapi: CIHaX9v6ps79IHANMutNxu7YmL9iE/54VWLLlRdJGkk=
    redis: F0r/4w0QLv+qe9xb0045ql/SraeNHxPCzTm7mFFOaPk=

  ingress:
    kas_dns: kas.lukasz.test
    
    annotations:
      cert-manager.io/cluster-issuer: plural
    

  redis:
    auth:
      password: F0r/4w0QLv+qe9xb0045ql/SraeNHxPCzTm7mFFOaPk=

