ownerEmail: lukasz@plural.sh




external-dns:
  enabled: false

plural-certmanager-webhook:
  enabled: false

operator:
  enabled: false

application:
  enabled: false

plural:
  enabled: false

ingress-nginx:
  enabled: false
ingress-nginx-private:
  enabled: false


